spring.application.name=journalApp
spring.data.mongodb.uri =  mongodb+srv://shparthhome_db_user:0jSlId6NxiGmMwkz@cluster0.jhr7xa2.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true